<h2>Infoscript erstellen</h2>
<h3>Bild Template gewählt</h3>

<div class="row well">
  <div class="col-lg-7">
    <?php echo $this->ztbform($this->form); ?>
    <p>Test skdgsdgnsd sd gsd d sgsdg gsd sdg sdg gsd dgs sg sg sd g sdg s g sdg g sdg gsd 
    hfgfgfg fg sdf gsdf g df  dfg df dg df g d  dg dg  dg fg df gd dg df dg dg</p>
  </div>
  <div class="col-lg-5">
    <iframe style="width: 1280px;height: 720px;-moz-transform: scale(0.35);-moz-transform-origin: 0px 0;"
            scrolling="no" src="/generator/index/bild"></iframe>
  </div>
</div>

<?php // $this->form->prepare();                   ?>

<?php // echo $this->form()->openTag($this->form)  ?>

<?php // echo $this->formCollection($this->form);  ?>

<?php // echo $this->formRow($this->form->getTitel());  //nur titel ausgeben, wenn es mehrere elemente / textboxen gibt ?>

<?php // echo $this->form()->closeTag($this->form) ?>

