<h2>Infoscript erstellen</h2>
<h3>Vorlage wählen</h3>

<!-- ------------------------------------------------------- FEHLERMELDUNGEN -->
<?php if($this->errorMessages) : ?>
<div class="panel panel-danger">
    <div class="panel-heading">
        Fehler:
    </div>
    <div class="panel-body">
        <ul>
        <?php foreach ($this->errorMessages as $error) : ?>
            <li> <?= $error ?>   </li>

        <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>




<div class="row row-fluid ">

    <div class="col-md-12 help-block">
        Bitte wählen Sie eine der vorgeschlagenen Vorlagen und klicken
        bei der passenden auf "auswählen".
    </div>

</div>



<div class="row">

    <!-- ----------------------------------------------------- Template Info -->
    <div class="col-md-4">
        <div class="panel panel-default">
            
            <div class="panel-heading">
                Info <a class="btn btn-default btn-sm pull-right" href="/fachhochschule/create/create-info"> auswählen </a>
            </div>
            
            <div class="panel-body">
                <iframe style="border: #000 none; width: 100%; height: 260px" src="http://docs.ispconfig.org/wp-content/uploads/2010/10/user-group-icon.png"></iframe>
            </div>
            
            <div class="panel-footer">
                Diese Vorlage wählen sie aus, wenn ...
            </div>
            
        </div>        
    </div>
    
    <!-- -------------------------------------------------- Template Tabelle -->
    <div class="col-md-4">
        <div class="panel panel-default">
            
            <div class="panel-heading">
                Tabelle <a class="btn btn-default btn-sm pull-right" href="/fachhochschule/create/create-tabelle"> auswählen </a>
            </div>
            
            <div class="panel-body">
                <iframe style="border: #000 none; width: 100%; height: 260px" src="http://docs.ispconfig.org/wp-content/uploads/2010/10/user-group-icon.png"></iframe>
            </div>
            
            <div class="panel-footer">
                Diese Vorlage wählen sie aus, wenn ...
            </div>
            
        </div>        
    </div>
    
    <!-- ----------------------------------------------------- Template Bild -->
    <div class="col-md-4">
        <div class="panel panel-default">
            
            <div class="panel-heading">
                Bild <a class="btn btn-default btn-sm pull-right" href="/fachhochschule/create/create-bild"> auswählen </a>
            </div>
            
            <div class="panel-body">
                <iframe style="border: #000 none; width: 100%; height: 260px" src="http://docs.ispconfig.org/wp-content/uploads/2010/10/user-group-icon.png"></iframe>
            </div>
            
            <div class="panel-footer">
                Diese Vorlage wählen Sie dann aus, wenn Ihr Infoscript aus
                einem Bild mit allen Informationen besteht.
            </div>
            
        </div>        
    </div>
    
    <!-- ----------------------------------------------------- Template Liste -->
    <div class="col-md-4">
        <div class="panel panel-default">
            
            <div class="panel-heading">
                Liste <a class="btn btn-default btn-sm pull-right" href="/fachhochschule/create/create-liste"> auswählen </a>
            </div>
            
            <div class="panel-body">
                <iframe style="border: #000 none; width: 100%; height: 260px" src="http://docs.ispconfig.org/wp-content/uploads/2010/10/user-group-icon.png"></iframe>
            </div>
            
            <div class="panel-footer">
                Diese Vorlage wählen Sie dann aus, wenn Ihr Infoscript aus
                eine Liste mit allen Informationen besteht.
            </div>
            
        </div>        
    </div>

</div>