<h2>Benutzerregistrierung</h2>
<h3>Organisation der FH Schmalkalden</h3>

<div class="row">

    <div class="col-md-12">
        <p>Als Organisation der FH Schmalkalden dürfen Sie Infoscripte, die in Beziehung zu der Organisation stehen, buchen.</p>
        <p>Als Studentenclub buchen Sie beispielsweise Infoscripte, die auf Club- Veranstaltungen hinweisen.</p>
    </div>

</div>

<div class="row">

    <div class="col-md-4">
        
        <div class="panel panel-default">
            <div class="panel-heading">
                Benutzerdaten:
            </div>
            <div class="panel-body">
                <div class="form">
                    
                    <?php $this->form->prepare(); ?>
                    
                    <?php echo $this->ztbForm($this->form); ?>

                </div>
                
                
            </div>
                
        </div>
        
    </div>

</div>