<?php
    $this->layout()->setVariable('tasks', array( 'neu' => array(
                    'icon'   => '/img/fachhochschule/icons/new-16.png',
                    'target' => '/fachhochschule/infoscript/create',
                )
            )
        );
?>


<h2 class="h2"> Administrator - Infoscripte Anzeigen </h2>

<div class="alert-success">
    <?php
        foreach ($this->msgSuccess as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>
<div class="alert-info">
    <?php
        foreach ($this->msgInfo as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>
<div class="alert-danger">
    <?php
        foreach ($this->msgError as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>



<?php



echo $this->partial('fachhochschule/index/partial/infoscript.phtml', [
    'user' => $this->user, 
    'current' => $this->current, 
    'future' => $this->future, 
    'outdated' => $this->outdated,
    
    'actionUrls' => $this->actionUrls,
]);
?>