
<h2>Infoscript Details</h2>

<div class="alert-success">
    <?php
        foreach ($this->msgSuccess as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>
<div class="alert-info">
    <?php
        foreach ($this->msgInfo as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>
<div class="alert-danger">
    <?php
        foreach ($this->msgError as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Meta Daten  </h3>
            </div>
            <div class="panel-body">
                <table class="table responsive table-striped table-hover">
                    <tbody>
                        <tr>
                            <th>ID</th>
                            <td><?= $this->infoscript->getInseratId(); ?></td>
                        </tr>
                        <tr>
                            <th>START</th>
                            <td><?= $this->infoscript->getStart();     ?></td>
                        </tr>
                        <tr>
                            <th>ENDE</th>
                            <td><?= $this->infoscript->getEnde();      ?></td>
                        </tr>
                        <tr>
                            <th>URL</th>
                            <td><?= $this->infoscript->getUrl();       ?></td>
                        </tr>

                    </tbody>


                </table>
            </div>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Bildschirme  </h3>
            </div>
            <div class="panel-body">
                <table class="table table-responsive table-striped table-hover">
                    <thead>
                        <tr>
                            <th>ID                     </th>
                            <th>BESCHREIBUNG           </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->infoscript->getBildschirme() as $bildschirm) : ?>
                        <tr>
                            <td><?= $bildschirm; ?></td>
                            <td></td>
                            <td><a class="btn-sm btn-danger pull-right" href=" <?=$this->deleteUrl . '/id=' . $this->infoscript->getInseratId() . "/display=$bildschirm" ?> "> löschen </a></td>
                        </tr>
                        <?php endforeach; ?>

                        <?php foreach ($this->bildschirme as $bildschirm) : ?>
                        <tr>
                            <td><?= $bildschirm; ?></td>
                            <td></td>
                            <td><a class="btn-sm btn-success pull-right" href=" <?=$this->addUrl . '/id=' . $this->infoscript->getInseratId() . "/display=$bildschirm" ?> "> hinzufügen </a></td>
                        </tr>
                        <?php endforeach; ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Status  </h3>
            </div>
            <div class="panel-body">
                <table class="table table-responsive table-hover">
                    <tr>
                        <th>Freigeschaltet</th>
                        <td><?= ($this->infoscript->getAktiv()) ? 'ja' : 'nein';     ?></td>
                    </tr>
                    <tr>
                        <th>Angezeigt</th>
                        <td><?= ($this->infoscript->isAngezeigt()) ? 'ja' : 'nein' ?> (<?= $this->infoscript->getStatus() ?>) </td>
                    </tr>
                    
                    
                </table>
            </div>
        </div>
    </div>
    
    
</div>

<div class="panel-body">
                <iframe style="
                    overflow: hidden;
                    width: 1280px;
                    height: 720px;
                    -ms-zoom: 0.5;
                    -moz-transform: scale(0.5);
                    -moz-transform-origin: 0px 0;
                    -o-transform: scale(0.5);
                    -o-transform-origin: 0 0;
                    -webkit-transform: scale(0.5);
                    -webkit-transform-origin: 0 0; 
                    " scrolling="no" src="<?= $this->infoscript->getUrl() ?>">
                </iframe>
            </div>



<?php

    /*
     * View- Variablen
     * -------------------------------------------------------------------------
     * $this->infoscript Infoscript, dessen Details angezeigt werden sollen
     * Test mit var_dump($this->infoscript);
     * Zugriff auf Eigenschaften über get- Methoden
     * 
     * $this->deleteUrl Url, die zum Löschen eines Infoscripts von einem
     * bestimmten Bildschirm führt.
     * inseratId und bildschirmId müssen als Parameter angehängt werden.
     */

?>
