<?php
    $this->layout()->setVariable('tasks', array( 'neu' => array(
                    'icon'   => '/img/administration/icons/new-16.png',
                    'target' => '/administration/infoscript/create',
                )
            )
        );
?>


<h2 class="h2"> Administrator - Infoscripte Anzeigen </h2>

<div class="alert-success">
    <?php
        foreach ($this->msgSuccess as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>
<div class="alert-info">
    <?php
        foreach ($this->msgInfo as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>
<div class="alert-danger">
    <?php
        foreach ($this->msgError as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>




<ul class="nav nav-tabs">
    <li class="active"><a href="#aktive"      data-toggle="tab">Aktive</a></li>
    <li>               <a href="#abgelaufene" data-toggle="tab">Abgelaufene</a></li>
    <li>               <a href="#zukuenftige" data-toggle="tab">Zukünftige</a></li>
</ul>

<div id='content' class="tab-content">

    <div class="tab-pane active" id="aktive">

        <table class="table table-responsive table-striped table-hover">

            <thead>
            <tr>
                <th>Details</th>
                <th>BId</th>
                <th>Start</th>
                <th>Ende</th>
                <th>Aktiv</th>
                <th>Url</th>
                <th>Bearbeiten</th>
                <th>Löschen</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($this->current as $value) : ?>
                <tr>

                    <td> <a class="btn btn-default btn-xs" href="<?= $this->urlDetails . '/id=' .$value->getInseratId() ?>">  <?php echo 'Details'    ?> </a> </td>
                    <td> <?php echo $value->getUserId()               ?>      </td>
                    <td> <?php echo $value->getStart();     ?>      </td>
                    <td> <?php echo $value->getEnde();      ?>      </td>
                    <td> <?php echo $value->getAktiv();     ?>      </td>
                    <td> <?php echo $value->getUrl();   ?>      </td>

                    <td> <a class="btn btn-default btn-xs" href="<?= $this->urlEdit   . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Bearbeiten'    ?> </a> </td>
                    <td> <a class="btn btn-danger btn-xs"  href="<?= $this->urlDelete . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Löschen'       ?> </a> </td>
                </tr>
                <?php endforeach; ?>
            </tbody>

        </table>


    </div>

    <div class="tab-pane" id="abgelaufene">

        <table class="table table-responsive table-striped table-hover">

            <thead>
            <tr>
                <th>Details</th>
                <th>BId</th>
                <th>Start</th>
                <th>Ende</th>
                <th>Aktiv</th>
                <th>Url</th>
                <th>Bearbeiten</th>
                <th>Löschen</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($this->outdated as $value) : ?>
                <tr>

                    <td> <a class="btn btn-default btn-xs" href="<?= $this->urlDetails . '/id=' .$value->getInseratId() ?>">  <?php echo 'Details'    ?> </a> </td>
                    <td> <?php echo $value->getUserId()               ?>      </td>
                    <td> <?php echo $value->getStart();     ?>      </td>
                    <td> <?php echo $value->getEnde();      ?>      </td>
                    <td> <?php echo $value->getAktiv();     ?>      </td>
                    <td> <?php echo $value->getUrl();   ?>      </td>

                    <td> <a class="btn btn-default btn-xs" href="<?= $this->urlEdit   . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Bearbeiten'    ?> </a> </td>
                    <td> <a class="btn btn-danger btn-xs"  href="<?= $this->urlDelete . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Löschen'       ?> </a> </td>
                </tr>
                <?php endforeach; ?>
            </tbody>

        </table>

    </div>

    <div class="tab-pane" id="zukuenftige">
        <table class="table table-responsive table-striped table-hover">

            <thead>
            <tr>
                <th>Details</th>
                <th>BId</th>
                <th>Start</th>
                <th>Ende</th>
                <th>Aktiv</th>
                <th>Url</th>
                <th>Bearbeiten</th>
                <th>Löschen</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($this->future as $value) : ?>
                <tr>

                    <td> <a class="btn btn-default btn-xs" href="<?= $this->urlDetails . '/id=' .$value->getInseratId() ?>">  <?php echo 'Details'    ?> </a> </td>
                    <td> <?php echo $value->getUserId()               ?>      </td>
                    <td> <?php echo $value->getStart();     ?>      </td>
                    <td> <?php echo $value->getEnde();      ?>      </td>
                    <td> <?php echo $value->getAktiv();     ?>      </td>
                    <td> <?php echo $value->getUrl();   ?>      </td>

                    <td> <a class="btn btn-default btn-xs" href="<?= $this->urlEdit   . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Bearbeiten'    ?> </a> </td>
                    <td> <a class="btn btn-danger btn-xs"  href="<?= $this->urlDelete . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Löschen'       ?> </a> </td>
                </tr>
                <?php endforeach; ?>
            </tbody>

        </table>
    </div>

</div>