<?php
    $this->layout()->setVariable('tasks', array( 'neu' => array(
                    'icon'   => '/img/administration/icons/new-16.png',
                    'target' => '/administration/infoscript/create',
                )
            )
        );
?>


<h2 class="h2"> Administrator - Infoscripte Anzeigen </h2>

<div class="alert-success">
    <?php
        foreach ($this->msgSuccess as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>
<div class="alert-info">
    <?php
        foreach ($this->msgInfo as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>
<div class="alert-danger">
    <?php
        foreach ($this->msgError as $msg) :
            echo $msg . '<br />';
        endforeach;
    ?>
</div>



<div>
    
    <h3>Aktuelle Infoscripte</h3>
    <table class="table table-hover table-responsive table-striped">
        <thead>
            <tr>
                <th>Details</th>
                <th>BId</th>
                <th>Start</th>
                <th>Ende</th>
                <th>Aktiv</th>
                <th>Url</th>
                <th>Bearbeiten</th>
                <th>Löschen</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->current as $value) : ?>
            <tr>

                <td> <a class="btn btn-default btn-xs" href="<?= $this->urlDetails . '/id=' .$value->getInseratId() ?>">  <?php echo 'Details'    ?> </a> </td>
                <td> <?php echo $value->getUserId()               ?>      </td>
                <td> <?php echo $value->getStart();     ?>      </td>
                <td> <?php echo $value->getEnde();      ?>      </td>
                <td> <?php echo $value->getAktiv();     ?>      </td>
                <td> <?php echo $value->getUrl();   ?>      </td>

                <td> <a class="btn btn-default btn-xs" href="<?= $this->urlEdit   . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Bearbeiten'    ?> </a> </td>
                <td> <a class="btn btn-danger btn-xs"  href="<?= $this->urlDelete . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Löschen'       ?> </a> </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    
    <h3>Abgelaufene Infoscripte</h3>
    <table class="table table-hover table-responsive table-striped">
        <thead>
            <tr>
                <th>Details</th>
                <th>BId</th>
                <th>Start</th>
                <th>Ende</th>
                <th>Aktiv</th>
                <th>Url</th>
                <th>Bearbeiten</th>
                <th>Löschen</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->outdated as $value) : ?>
            <tr>

                <td> <a class="btn btn-default btn-xs" href="<?= $this->urlDetails . '/id=' .$value->getInseratId() ?>">  <?php echo 'Details'    ?> </a> </td>
                <td> <?php echo $value->getUserId()           ?>      </td>
                <td> <?php echo $value->getStart(); ?>      </td>
                <td> <?php echo $value->getEnde();  ?>      </td>
                <td> <?php echo $value->getAktiv(); ?>      </td>
                <td> <?php echo $value->getUrl();   ?>      </td>

                <td> <a class="btn btn-default btn-xs" href="<?= $this->urlEdit   . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Bearbeiten'    ?> </a> </td>
                <td> <a class="btn btn-danger btn-xs"  href="<?= $this->urlDelete . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Löschen'       ?> </a> </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    
    
    <h3>Zukünftige Infoscripte</h3>
    <table class="table table-hover table-responsive table-striped">
        <thead>
            <tr>
                <th>Details</th>
                <th>BId</th>
                <th>Start</th>
                <th>Ende</th>
                <th>Aktiv</th>
                <th>Url</th>
                <th>Bearbeiten</th>
                <th>Löschen</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->future as $value) : ?>
            <tr>

                <td> <a class="btn btn-default btn-xs" href="<?= $this->urlDetails . '/id=' .$value->getInseratId() ?>">  <?php echo 'Details'    ?> </a> </td>
                <td> <?php echo $value->getUserId()           ?>      </td>
                <td> <?php echo $value->getStart(); ?>      </td>
                <td> <?php echo $value->getEnde();  ?>      </td>
                <td> <?php echo $value->getAktiv(); ?>      </td>
                <td> <?php echo $value->getUrl();   ?>      </td>

                <td> <a class="btn btn-default btn-xs" href="<?= $this->urlEdit   . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Bearbeiten'    ?> </a> </td>
                <td> <a class="btn btn-danger btn-xs"  href="<?= $this->urlDelete . '/id=' . $value->getInseratId()  ?>">  <?php echo 'Löschen'       ?> </a> </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    
    
</div>