<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Liste Template</title>
        <link href="/css/generator/liste.css" rel="stylesheet" type="text/css"/>
    </head>
    <body>
        <div class="bg" style="background-image: url('/img/generator/bg.jpg')">

            <div class="header">

                <div class="headline">
                    <div class="datum"><?php echo date("d.m.Y") ?></div>

                    <div class="titel" id="headline"><?php echo $this->infoscript->getHeadline() ?> </div>

                    <div class="uhr"></div>
                </div>

            </div>

            <div class="row-fluid">
                <div class="col-md-12">

                    <div class="liste">

                        <div class="info">
                            <div class="column-title" id="columntitle"><?php echo $this->infoscript->getFirstColumn()->getTitle(); ?> </div>
                            <br>
                            <div class="column-text" id="columntext"><?php echo $this->infoscript->getFirstColumn()->getText(); ?> </div>
                        </div>

                    </div>

                </div>
            </div>
            <div class="bottom">powered by www.fh-schmalkalden.de</div>
        </div>
    </body>
</html>
