<h2>Benutzer löschen</h2>

<?php $this->form->setAttribute('action', $this->formAction); ?>
<?php $this->form->getId()->setValue($this->user->getUserId()); ?>

<?php $this->form->prepare(); ?>

<div class="row">

    <div class="col-md-5">

        <div class="panel panel-danger">
            <div class="panel-heading">
                <h4>Sicherheitsfrage</h4>
            </div>
            <div class="panel-body text-center">
                <p>Sind Sie sicher dass sie diesen Benutzer löschen möchten?</p>
                <p class="text-danger">Dabei werden alle Inserate des Benutzers gelöscht!</p>
                <p></p>
                <div class="row row-fluid">
                    <?php echo $this->form()->openTag($this->form); ?>

                    <div class="col-md-6">
                        <?php echo $this->formRow($this->form->getYes()); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formRow($this->form->getNo()); ?>
                    </div>

                    <?php echo $this->form()->closeTag($this->form); ?>
                </div>
            </div>
        </div>
    </div>

</div>