<h1 class="h1">Benutzer Administration</h1>


<?= $this->partial('base/flash.phtml'); ?>


<ul class="nav nav-tabs">
    <li class="active"><a href="#fachhochschule"      data-toggle="tab">Fachhochschule</a></li>
    <li>               <a href="#unternehmen"         data-toggle="tab">Unternehmen</a></li>
    <li>               <a href="#studenten"        data-toggle="tab">Studenten</a></li>
</ul>

<div id='content' class="tab-content">

    <div class="tab-pane active" id="fachhochschule">

        <?php echo $this->partial('base/user/partial/user-table.phtml'); ?>

    </div>

    
    <div class="tab-pane" id="unternehmen">

        <?php echo $this->partial('base/user/partial/user-table.phtml', ['users' => []]); ?>
        <div class="alert-danger">noch nicht implementiert</div>

    </div>

    
    <div class="tab-pane" id="studenten">

        
        <?php echo $this->partial('base/user/partial/user-table.phtml', ['users' => []]); ?>
        <div class="alert-danger">noch nicht implementiert</div>

    </div>

</div>







</div>

    <?php //var_dump($this->user);?>

</div>
