<h2>Willkommen, <?= $this->user->getName(); ?> </h2>

<div class="row row-fluid">

    <div class="col-md-6">
        <?php echo $this->partial('base/user/partial/user-data.phtml', ['user' => $this->user]); ?>
    </div>

    <div class="col-md-6">
        <?php echo $this->partial('base/user/partial/user-settings.phtml', ['user' => $this->user]); ?>
    </div>

</div>


<?php echo $this->partial('base/infoscript/partial/infoscript.phtml'); ?>