<div class="bg" style="background-image: url('/img/bg.jpg')">
  <div class="header">
    <div class="headline">
      <div class="datum">
        <?php echo date("d.m.Y") ?>
      </div>
      <div class="titel">
        <?php echo $this->headline."<br>"; ?>
      </div>
      <div class="uhr">

      </div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="col-md-12">
      <div class="liste">
        <center>
        <img src="<?php echo $this->bild ?>" width="1250" height="525" >
        </center>
      </div>
    </div>
  </div>
  <div class="bottom">powered by www.fh-schmalkalden.de</div>
</div>