<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Liste Template</title>
	<link href="/css/generator/liste.css" rel="stylesheet" type="text/css"/>
</head>
<body>
  <div class="bg" style="background-image: url('/img/generator/bg.jpg')">
  <div class="header">
    <div class="headline">
      <div class="datum">
        <?php echo date("d.m.Y") ?>
      </div>
      <div class="titel">
        <?php echo $this->headline."<br>"; ?>
      </div>
      <div class="uhr">

      </div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="col-md-12">
      <div class="liste">
        <div class="info">
          <?php echo $this->titel; ?>
          <br>
          <br>
          <?php echo $this->text; ?>
        </div>
      </div>
    </div>
  </div>
  <div class="bottom">powered by www.fh-schmalkalden.de</div>
</div>


</body>
</html>

