<?php echo $this->doctype(); ?>

<html lang="en">
    <head>


    </head>
    <body>
        <h1>MODULE - OWN GENERIC LAYOUT</h1>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                footer
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
